version: '3.6'
services:
  iris:
    #image: containers.intersystems.com/intersystems/irishealth-community-arm64:2023.2.0.227.0
    #image: containers.intersystems.com/intersystems/irishealth-community:2023.2.0.227.0
    #image: intersystemsdc/iris-community:2023.2-zpm
    image: intersystemsdc/irishealth-community
    #image: intersystemsdc/irishealth-ml-community
    hostname: katas-iris
    container_name: katas-iris
    ports:
      - 52773:52773
      - 1972:1972
      - 1980:1980
      - 1981:1981
      - 1982:1982
      - 1983:1983
      - 1984:1984
    command:
      - --check-caps false
      - --password-file /shared/pass.txt
    volumes:
      - type: bind
        source: ./iris-shared
        target: /shared
      - type: bind
        source: ./iris-test
        target: /home/irisowner/Test
    environment:
      - ISC_DATA_DIRECTORY=/shared/iris
  mysql:
    hostname: mysql
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'iris'
      MYSQL_USER: 'iris'
      MYSQL_PASSWORD: 'iris'
      MYSQL_ROOT_PASSWORD: 'iris'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - type: bind
        source: ./mysql-shared
        target: /var/lib/mysql
    command: 
      - --default-authentication-plugin=mysql_native_password
