version: '3.6'
services:
  iris:
    #image: containers.intersystems.com/intersystems/irishealth-community-arm64:2023.2.0.227.0
    #image: containers.intersystems.com/intersystems/irishealth-community:2023.2.0.227.0
    image: intersystemsdc/iris-community:2023.2-zpm
    hostname: katas-iris
    container_name: katas-iris
    ports:
      - 51773:51773
      - 52773:52773
      - 53773:53773
      - 54773:54773
      - 2188:2188
      - 1972:1972
      - 9980:9980
      - 1980:1980
    command:
      - --check-caps false
      - --password-file /shared/pass.txt
    volumes:
      - type: bind
        source: ./iris-shared
        target: /shared
    environment:
      - ISC_DATA_DIRECTORY=/shared/iris
  mysql:
    hostname: mysql
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'iris'
      MYSQL_USER: 'iris'
      MYSQL_PASSWORD: 'iris'
      MYSQL_ROOT_PASSWORD: 'iris'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - type: bind
        source: ./mysql-shared
        target: /var/lib/mysql
