Class cysnet.mario.wc.MiServicio.req.crearPersonaResponse Extends Ens.Response [ ProcedureBlock ]
{

Property crearPersonaResult As cysnet.mario.wc.MiServicio.s0.CrearPersonaResponse1;

Storage Default
{
<Data name="crearPersonaResponseDefaultData">
<Subscript>"crearPersonaResponse"</Subscript>
<Value name="1">
<Value>crearPersonaResult</Value>
</Value>
</Data>
<DefaultData>crearPersonaResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
