Class cysnet.mario.wc.MiServicio.req.obtenerPersonaResponse Extends Ens.Response [ ProcedureBlock ]
{

Property obtenerPersonaResult As cysnet.mario.wc.MiServicio.s0.ObtenerPersonaResponse1;

Storage Default
{
<Data name="obtenerPersonaResponseDefaultData">
<Subscript>"obtenerPersonaResponse"</Subscript>
<Value name="1">
<Value>obtenerPersonaResult</Value>
</Value>
</Data>
<DefaultData>obtenerPersonaResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
