/// Creado desde: http://localhost:52773/csp/mario/cysnet.mario.ws.MiServicio.cls?WSDL
Class cysnet.mario.wc.MiServicio.s0.CrearPersonaResponse1 Extends cysnet.mario.wc.MiServicio.s0.EnsResponse [ ProcedureBlock ]
{

Parameter ELEMENTQUALIFIED = 1;

Parameter NAMESPACE = "http://tempuri.org";

Parameter XMLNAME = "CrearPersonaResponse";

Parameter XMLTYPE = "CrearPersonaResponse";

Storage Default
{
<Type>%Storage.Serial</Type>
}

}
