/// Creado desde: http://localhost:52773/csp/mario/cysnet.mario.ws.MiServicio.cls?WSDL
Class cysnet.mario.wc.MiServicio.s0.EnsMessagebody Extends (%SerialObject, %XML.Adaptor) [ ProcedureBlock ]
{

Parameter ELEMENTQUALIFIED = 1;

Parameter NAMESPACE = "http://tempuri.org";

Parameter XMLNAME = "Ens_Messagebody";

Parameter XMLSEQUENCE = 1;

Parameter XMLTYPE = "Ens_Messagebody";

Storage Default
{
<StreamLocation>^cysnet.mari5850.EnsMessagebodyS</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
